### ISSUE TITLE
An issue about I2C in STM32F1

### ISSUE THREAD

**Issue by ideaRunner** [toxygen/mlab-chibios#2]
Hi, toxygen
    Sorry to interrupt you. May I ask you a question?
    I have a problem with GPIO mode set with I2C in ChibiOS.
    How could I use PAL_MODE_ALTERNATE? 
    I think I2C should use Alternate mode and OD mode. But I do not know how to set up it with STM32F1. 
    Should I include `pal_lld.c `and use `lld` function?

**Comment by toxygen** [comment]
either use palSetPadMode() like that:
palSetPadMode(GPIOA, 2, PAL_MODE_ALTERNATE(7));

or have a look in STM32F103/boards/MLAB_STM32F107RxT01A/board.h for sample default board config
